//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawnaThai_Eiei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Cooperative
    {
        public string AD_ID { get; set; }
        public string AD_Password { get; set; }
        public string AD_Name { get; set; }
        public string AD_Lastname { get; set; }
        public string AD_Tel { get; set; }
        public string Coop_Name { get; set; }
    
        public virtual Cooperative Cooperative { get; set; }
    }
}
